replicaCount: 1

image:
  repository: 149744648448.dkr.ecr.us-east-2.amazonaws.com/poc-mambu/poc-loan-account-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  externalPort: 18000
